- name: Get running processes list from remote host
      ignore_errors: yes
      shell: "ps -few | grep tomcat | awk '{print $2}'"
      register: running_processes
 
    - name: Kill running processes
      ignore_errors: yes
      shell: "kill {{ item }}"
      with_items: "{{ running_processes.stdout_lines }}"
 
    - wait_for:
        path: "/proc/{{ item }}/status"
        state: absent
      with_items: "{{ running_processes.stdout_lines }}"
      ignore_errors: yes
      register: tomcat
 
    - name: Force kill stuck processes
      ignore_errors: yes
      shell: "kill -9 {{ item }}"
      with_items: "{{ tomcat.results | select('failed') | map(attribute='item') | list }}"
